### ISSUE TITLE
Incompatibility with requests 2.11.1

### ISSUE THREAD

**Issue by napalmer7** [ThreatConnect-Inc/threatconnect-python#20]
I am working on an app and ran a test on a new system that installed requests v2.11.1. This version added a header validation which incorrectly handles integer values for headers such as Content-Length. [ThreatConnect.RequestObject (line 68)](https://github.com/ThreatConnect-Inc/threatconnect-python/blob/master/threatconnect/RequestObject.py#L68) sets the Content-Length using:

`self._headers['Content-Length'] = len(self._body)`

This causes request to raise the following exception:
```
Traceback (most recent call last):
  File "dg_tc.py", line 173, in <module>
    "TLP Red")
  File "dg_tc.py", line 78, in process_data
    indicator.commit()
  File "/home/tester/.local/lib/python2.7/site-packages/threatconnect/IndicatorObject.py", line 1193, in commit
    api_response = self._tc.api_request(ro)
  File "/home/tester/.local/lib/python2.7/site-packages/threatconnect/ThreatConnect.py", line 289, in api_request
    request_prepped.prepare_headers(ro.headers)
  File "/home/tester/.local/lib/python2.7/site-packages/requests/models.py", line 409, in prepare_headers
    check_header_validity(header)
  File "/home/tester/.local/lib/python2.7/site-packages/requests/utils.py", line 800, in check_header_validity
    "not %s" % (value, type(value)))
requests.exceptions.InvalidHeader: Header value 142 must be of type str or bytes, not <type 'int'>
```
I believe this a bug in requests and have logged an issue against them(https://github.com/kennethreitz/requests/issues/3559), but it does raise an incompatibility with the ThreatConnect SDK.

Using up to requests v2.11.0 works successfully on all platforms.

**Comment by tc-turner** [comment]
I will do some testing to see what happens if we cast that to a str.  By looking at their other issues surrounding this the implication is that all versions of requests will support and are intended for header values to str.

**Comment by napalmer7** [comment]
Yes... although I don't agree with their logic, and it seems to go against the RFC (https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.13), their documentation does state it has to be a string.

http://docs.python-requests.org/en/master/user/quickstart/#custom-headers

**Comment by nateprewitt** [comment]
For further clarification, the reason Requests only supports strings/bytes is that is the only format that makes sense. The concept of `int` doesn't exist in HTTP, there is no typing system, only [characters in strings](https://github.com/kennethreitz/requests/pull/3366#commitcomment-18581242). Also note that RFC2616 is deprecated and replaced by [RFC7230](https://tools.ietf.org/html/rfc7230#section-3.2), which very clearly states this.

One last thing to check is that it is 2.11.0, and not 2.10.0, that doesn't produce this error. This change was introduced in 2.11.0, not 2.11.1, so both versions are identical in this regard.

@tc-turner converting your `len(self._body)` call by wrapping it in `str()` should work just fine for this case :)

**Comment by napalmer7** [comment]
@nateprewitt, you are correct I double checked my test systems and I mistyped the functional version (v2.10.0).

**Comment by tc-turner** [comment]
@nateprewitt That was my plan, I'll submit a PR tonight for review by our maintainer tomorrow.

**Comment by tc-turner** [comment]
#22

**Comment by tc-turner** [comment]
@napalmer7 @nateprewitt  This has been addressed in develop branch.
[3a5300e85004e4daf5abd51deffbe82a1aa9f29f](https://github.com/ThreatConnect-Inc/threatconnect-python/commit/3a5300e85004e4daf5abd51deffbe82a1aa9f29f)

**Comment by tc-turner** [comment]
Closing this since it will be addressed in the next release.
