### ISSUE TITLE
Support for New Indicator Types

### ISSUE THREAD

**Issue by BaddaBoom** [ThreatConnect-Inc/threatconnect-python#26]
With the October 4.4 release, there is support added for ASNs, registry keys, mutexes, CIDRs, and user agent strings. The current Indicatortype.py and resourcetype.py enum configs do not provide explicit support for these. Is there a solution to committing these types of indicators and/or is ThreatConnect releasing an updated codebase to reflect these additions.

**Comment by bcsummers** [comment]
Version 2.4.14 has support for Custom Indicator types.
