### ISSUE TITLE
Log to threatconnect Not Root Logger

### ISSUE THREAD

**Issue by utkonos** [ThreatConnect-Inc/threatconnect-python#38]
The way the threatconnect package logs right now, everything ends up in the root logger. If I want to write a tc.log file using the following, the main logs will still contain all the same log entries from this file.
`tc.set_tcl_file(tc_log_location, log_level)`

The correct way to form these log entries is to name the logger `threatconnect` so that these logs can be filtered out from the root logger if someone is running multiple packages all with different logging and all wanting to go to different log streams. This is achieved by:
```
import logging
logging.getLogger('threatconnect').addHandler(logging.NullHandler())
```

Or something very similar. This is covered in the logging HOWTO section "Configuring Logging for a Library" here:
https://docs.python.org/3/howto/logging.html#logging-advanced-tutorial

**Comment by bcsummers** [comment]
Closed per research.
