### ISSUE TITLE
  raise AttributeError(ErrorCodes.e10050.name.format(indicator)) AttributeError: e10050

### ISSUE THREAD

**Issue by omaidf** [ThreatConnect-Inc/threatconnect-python#68]
def tcfile(filehash,description):
	indicators = tc.indicators()
	print "Hash: %s\nDescription: %s\nOwner: %s" % (filehash,description,owner)
	indicator = indicators.add(filehash,owner)
	indicator.add_attribute(description)
	indicator.set_confidence(75)
	indicator.set_rating(2.5)
	indicator.commit()

Error:    raise AttributeError(ErrorCodes.e10050.name.format(indicator))
AttributeError: e10050

**Comment by utkonos** [comment]
Can you show what the contents of the variable you call "description"? The .add_attribute() method requires two parameters. Here is the documentation for creating a file indicator:
https://docs.threatconnect.com/en/latest/python/python_sdk.html#create-files

**Comment by utkonos** [comment]
I think as you have it, you're missing the second parameter for .add_attribute()

Try:
```
indicator.add_attribute('Description', description)
```

**Comment by omaidf** [comment]
Fixed this, thanks!
