### ISSUE TITLE
URL indicator - port starting with 0 (cero) is taken as invalid

### ISSUE THREAD

**Issue by kdeltared** [ThreatConnect-Inc/threatconnect-python#77]
Using the batch API to commit indicators I get this error when I try to upload `http://149.56.254.105:0303/web01.zip` as URL.

The response is:
`Batch Job 520060 errors: [{"errorReason":"The value is not a valid URL.","errorSource":"http://149.56.254.105:0303/web01.zip"}]`

If I change the port to 303 it works

**Comment by gsopko-tc** [comment]
Sockets are an integer between 1-65535, and 0 is reserved and by having that leading 0 Python probably exited as it's not valid. That actual message, The value is not a valid URL, is probably from Python itself and not from our SDK as I could not find the logic for it, we simply passed the trapped message along.

I'd suggest to research URL validation via available Python modules such as URLValidator, or a regex expression, amongst other common methods.

**Comment by kdeltared** [comment]
Thanks for the answer. When trying to upload the same URL usign the frontend I have the same problem. Looks like a backend validation.

![image](https://user-images.githubusercontent.com/14323062/47513225-2ab29800-d854-11e8-92e2-1e875c2c9982.png)
